CREATE WAREHOUSE IF NOT EXISTS TP_REPORTING_WH
    WAREHOUSE_SIZE = XSMALL
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

USE WAREHOUSE TP_REPORTING_WH;

CREATE DATABASE IF NOT EXISTS TRASH_PANDAS_CONNECTED_REPORTING;

USE DATABASE TRASH_PANDAS_CONNECTED_REPORTING;

CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS ANALYTICS;
CREATE SCHEMA IF NOT EXISTS QA;

CREATE OR REPLACE FILE FORMAT RAW.CSV_EXPORT_FORMAT
    TYPE = CSV
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    TRIM_SPACE = TRUE
    EMPTY_FIELD_AS_NULL = FALSE
    ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE;

CREATE OR REPLACE STAGE RAW.TP_EXPORT_STAGE
    FILE_FORMAT = RAW.CSV_EXPORT_FORMAT;

USE SCHEMA RAW;

SELECT
    CURRENT_WAREHOUSE() AS current_warehouse,
    CURRENT_DATABASE() AS current_database,
    CURRENT_SCHEMA() AS current_schema;

SHOW SCHEMAS IN DATABASE TRASH_PANDAS_CONNECTED_REPORTING;

SHOW FILE FORMATS IN SCHEMA RAW;

SHOW STAGES IN SCHEMA RAW;