USE ROLE ACCOUNTADMIN;
USE WAREHOUSE TP_REPORTING_WH;
USE DATABASE TRASH_PANDAS_CONNECTED_REPORTING;
USE SCHEMA RAW;

TRUNCATE TABLE RAW.HOMESTAND_SUMMARY;
TRUNCATE TABLE RAW.PROMOTION_SCORECARD;
TRUNCATE TABLE RAW.CRM_FOLLOW_UP_QUEUE;

COPY INTO RAW.HOMESTAND_SUMMARY
FROM @RAW.TP_EXPORT_STAGE/homestand_summary.csv
FILE_FORMAT = RAW.CSV_EXPORT_FORMAT
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = ABORT_STATEMENT;

COPY INTO RAW.PROMOTION_SCORECARD
FROM @RAW.TP_EXPORT_STAGE/promotion_scorecard.csv
FILE_FORMAT = RAW.CSV_EXPORT_FORMAT
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = ABORT_STATEMENT;

COPY INTO RAW.CRM_FOLLOW_UP_QUEUE
FROM @RAW.TP_EXPORT_STAGE/crm_follow_up_queue.csv
FILE_FORMAT = RAW.CSV_EXPORT_FORMAT
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = ABORT_STATEMENT;

SELECT 'HOMESTAND_SUMMARY' AS table_name, COUNT(*) AS row_count
FROM RAW.HOMESTAND_SUMMARY

UNION ALL

SELECT 'PROMOTION_SCORECARD' AS table_name, COUNT(*) AS row_count
FROM RAW.PROMOTION_SCORECARD

UNION ALL

SELECT 'CRM_FOLLOW_UP_QUEUE' AS table_name, COUNT(*) AS row_count
FROM RAW.CRM_FOLLOW_UP_QUEUE;