USE WAREHOUSE TP_REPORTING_WH;
USE DATABASE TRASH_PANDAS_CONNECTED_REPORTING;

CREATE OR REPLACE VIEW ANALYTICS.V_HOMESTAND_SUMMARY AS
SELECT
    season,
    homestand_id,
    homestand_start_date,
    homestand_end_date,
    game_count,
    weekend_game_count,
    opponents,
    public_announced_attendance,
    matched_attendance_game_count,
    tickets_sold,
    scanned_attendance,
    scan_rate,
    no_show_ticket_quantity,
    no_show_rate,
    ticket_order_count,
    unique_ticket_buyers,
    net_ticket_revenue,
    group_ticket_quantity,
    group_ticket_revenue,
    group_sale_count,
    group_renewal_opportunity_count,
    group_upsell_opportunity_count,
    merch_transaction_count,
    merch_net_sales,
    fan_matched_merch_transactions,
    concession_transaction_count,
    concession_net_sales,
    fan_matched_concession_transactions,
    revenue_per_scanned_fan,
    merch_per_scanned_fan,
    concession_per_scanned_fan,
    in_park_spend_per_scanned_fan,
    total_revenue_indicator,
    promotion_count,
    primary_promo_count,
    giveaway_count,
    fireworks_count,
    theme_night_count,
    family_promo_count,
    promo_categories,
    sponsorship_activation_count,
    unique_sponsor_count,
    sponsorship_goals,
    fan_engagement_count,
    unique_engaged_fans,
    avg_engagement_score,
    follow_up_opportunity_count,
    high_priority_opportunity_count,
    medium_priority_opportunity_count,
    crm_follow_up_task_count,
    sales_task_count,
    marketing_task_count,
    service_task_count,
    group_sales_task_count,
    future_revenue_opportunity,
    avg_opportunity_score,
    homestand_total_value_index,
    recommended_focus
FROM RAW.HOMESTAND_SUMMARY;

CREATE OR REPLACE VIEW ANALYTICS.V_PROMOTION_SCORECARD AS
SELECT
    promo_id,
    game_id,
    season,
    game_date,
    homestand_id,
    opponent,
    day_of_week,
    weekend_flag,
    promo_name,
    promo_category,
    promo_type,
    primary_promo_flag,
    sponsor_attached_flag,
    giveaway_flag,
    fireworks_flag,
    theme_night_flag,
    family_flag,
    dog_day_flag,
    jersey_auction_flag,
    expected_fan_segment,
    public_announced_attendance,
    tickets_sold,
    scanned_attendance,
    scan_rate,
    no_show_ticket_quantity,
    no_show_rate,
    ticket_order_count,
    unique_ticket_buyers,
    repeat_buyer_count,
    repeat_buyer_rate,
    group_tickets,
    group_revenue,
    merch_net_sales,
    concession_net_sales,
    revenue_per_scanned_fan,
    merch_per_scanned_fan,
    concession_per_scanned_fan,
    in_park_spend_per_scanned_fan,
    total_revenue_indicator,
    fan_engagement_count,
    unique_engaged_fans,
    avg_engagement_score,
    follow_up_opportunity_count,
    high_priority_opportunity_count,
    crm_follow_up_task_count,
    future_revenue_opportunity,
    baseline_scanned_attendance,
    baseline_merch_per_scanned_fan,
    baseline_concession_per_scanned_fan,
    baseline_revenue_per_scanned_fan,
    baseline_repeat_buyer_rate,
    scanned_attendance_lift_vs_slot,
    merch_lift_per_scanned_fan,
    concession_lift_per_scanned_fan,
    revenue_lift_per_scanned_fan,
    repeat_buyer_rate_lift_vs_slot,
    total_value_index,
    recommendation,
    recommendation_reason
FROM RAW.PROMOTION_SCORECARD;

CREATE OR REPLACE VIEW ANALYTICS.V_CRM_FOLLOW_UP_QUEUE AS
SELECT
    priority_rank,
    follow_up_id,
    opportunity_id,
    entity_type,
    entity_id,
    entity_display_name,
    assigned_team,
    assigned_owner,
    executive_action_bucket,
    priority_score,
    priority_band,
    opportunity_type,
    opportunity_reason,
    source_signal,
    suggested_action,
    due_date,
    status,
    created_date,
    future_revenue_opportunity,
    repeat_likelihood_score,
    upgrade_potential_score,
    entity_total_value,
    entity_ticket_revenue,
    entity_in_park_revenue,
    entity_activity_summary,
    dashboard_filter_label,
    game_id,
    season,
    TRY_TO_DATE(game_date) AS game_date,
    opponent,
    day_of_week,
    homestand_id,
    promo_names,
    promo_categories,
    promo_types,
    fan_id,
    fan_segments,
    market_distance_band,
    email_opt_in_flag,
    sms_opt_in_flag,
    family_flag,
    corporate_flag,
    youth_sports_flag,
    fan_ticket_order_count,
    fan_ticket_quantity,
    fan_ticket_revenue,
    fan_games_purchased,
    fan_games_attended,
    fan_scan_rate,
    fan_no_show_rate,
    fan_merch_revenue,
    fan_concession_revenue,
    fan_in_park_revenue,
    fan_total_value,
    fan_hidden_value_flag,
    fan_engagement_count,
    fan_avg_engagement_score,
    TRY_TO_DATE(fan_last_purchase_date) AS fan_last_purchase_date,
    TRY_TO_DATE(fan_last_attended_date) AS fan_last_attended_date,
    TRY_TO_DATE(fan_last_engagement_date) AS fan_last_engagement_date,
    account_id,
    account_name,
    account_type,
    account_owner,
    industry,
    city,
    zip_code,
    renewal_status,
    account_group_sale_count,
    account_group_ticket_quantity,
    account_group_revenue,
    account_avg_group_scan_rate,
    account_renewal_opportunity_count,
    account_upsell_opportunity_count,
    account_total_value,
    synthetic_data_flag
FROM RAW.CRM_FOLLOW_UP_QUEUE;

CREATE OR REPLACE VIEW ANALYTICS.V_EXECUTIVE_HOMESTAND_OVERVIEW AS
SELECT
    season,
    homestand_id,
    homestand_start_date,
    homestand_end_date,
    game_count,
    opponents,
    tickets_sold,
    scanned_attendance,
    scan_rate,
    no_show_ticket_quantity,
    no_show_rate,
    net_ticket_revenue,
    merch_net_sales,
    concession_net_sales,
    total_revenue_indicator,
    revenue_per_scanned_fan,
    in_park_spend_per_scanned_fan,
    follow_up_opportunity_count,
    crm_follow_up_task_count,
    future_revenue_opportunity,
    homestand_total_value_index,
    recommended_focus
FROM ANALYTICS.V_HOMESTAND_SUMMARY;

CREATE OR REPLACE VIEW ANALYTICS.V_PROMOTION_RECOMMENDATION_SUMMARY AS
SELECT
    season,
    promo_category,
    recommendation,
    COUNT(DISTINCT promo_id) AS promotion_count,
    ROUND(AVG(total_value_index), 2) AS avg_total_value_index,
    ROUND(AVG(scanned_attendance), 2) AS avg_scanned_attendance,
    ROUND(AVG(scan_rate), 4) AS avg_scan_rate,
    ROUND(AVG(no_show_rate), 4) AS avg_no_show_rate,
    ROUND(AVG(revenue_per_scanned_fan), 2) AS avg_revenue_per_scanned_fan,
    ROUND(AVG(in_park_spend_per_scanned_fan), 2) AS avg_in_park_spend_per_scanned_fan,
    ROUND(SUM(total_revenue_indicator), 2) AS total_revenue_indicator,
    ROUND(SUM(future_revenue_opportunity), 2) AS total_future_revenue_opportunity
FROM ANALYTICS.V_PROMOTION_SCORECARD
GROUP BY
    season,
    promo_category,
    recommendation;

CREATE OR REPLACE VIEW ANALYTICS.V_CRM_ACTION_BUCKET_SUMMARY AS
SELECT
    assigned_team,
    executive_action_bucket,
    priority_band,
    entity_type,
    COUNT(DISTINCT follow_up_id) AS task_count,
    ROUND(SUM(future_revenue_opportunity), 2) AS total_future_revenue_opportunity,
    ROUND(AVG(priority_score), 2) AS avg_priority_score,
    ROUND(AVG(repeat_likelihood_score), 2) AS avg_repeat_likelihood_score,
    ROUND(AVG(upgrade_potential_score), 2) AS avg_upgrade_potential_score
FROM ANALYTICS.V_CRM_FOLLOW_UP_QUEUE
GROUP BY
    assigned_team,
    executive_action_bucket,
    priority_band,
    entity_type;

SHOW VIEWS IN SCHEMA ANALYTICS;